/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dataBase.SalvarBemAtivo;
import iquiscbaii.BemAtivoJar;
import iquiscbaii.NotaFiscalJar;
import iquiscbaii.SetorJar;
import iquiscbaii.UnidadeJar;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class BemAtivoJFrame extends javax.swing.JFrame {
    
    BemAtivoJar objBemAtivo;

    /**
     * Creates new form BemAtivoJFrame
     */
    public BemAtivoJFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
        URL url = this.getClass().getResource("./img/comp16.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        
        SalvarBemAtivo DAO = new SalvarBemAtivo();
        try{
            DefaultComboBoxModel jcbNF = new DefaultComboBoxModel(DAO.todasAsNotas().toArray());
            jcbNotaFiscal.setModel(jcbNF);
            
            DefaultComboBoxModel jcbUni = new DefaultComboBoxModel(DAO.todasUnidades().toArray());
            jcbUnidade.setModel(jcbUni);
            
            DefaultComboBoxModel jcbSet = new DefaultComboBoxModel(DAO.todosSetor().toArray());
            jcbSetor.setModel(jcbSet);
        }catch(SQLException ex){
            Logger.getLogger(BemAtivoJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbNotaFiscal = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jcbUnidade = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entradaFabricante = new javax.swing.JTextField();
        entradaModelo = new javax.swing.JTextField();
        entradaSerialNumber = new javax.swing.JTextField();
        entradaNumeroImobilizado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        entradaDescricao = new javax.swing.JTextPane();
        jbuttonSalvar = new javax.swing.JButton();
        jbuttonCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcbSetor = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Bem Ativo");

        jLabel1.setText("Nota Fiscal: ");

        jcbNotaFiscal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        jcbNotaFiscal.setToolTipText("Selecione a Nota Fiscal de acordo com seu respectivo número");
        jcbNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNotaFiscalActionPerformed(evt);
            }
        });

        jLabel2.setText("Unidade: ");

        jcbUnidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        jcbUnidade.setToolTipText("Selecione a Unidade onde será instalado");

        jLabel3.setText("Fabricante:  ");

        jLabel4.setText("Modelo: ");

        jLabel5.setText("Número de Série: ");

        jLabel6.setText("Número Imobilizado: ");

        jLabel7.setText("Descrição: ");

        entradaFabricante.setToolTipText("Informe o fabricante");

        entradaModelo.setToolTipText("Informe o Modelo");

        entradaSerialNumber.setToolTipText("Informe o Número de Série");

        entradaNumeroImobilizado.setToolTipText("Informe o Número do Imobilizado");

        entradaDescricao.setToolTipText("Digite uma breve descrição sobre o Bem Imobilizado");
        jScrollPane1.setViewportView(entradaDescricao);

        jbuttonSalvar.setText("Salvar");
        jbuttonSalvar.setToolTipText("Clique para Salvar");
        jbuttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSalvarActionPerformed(evt);
            }
        });

        jbuttonCancelar.setText("Cancelar");
        jbuttonCancelar.setToolTipText("Clique para Cancelar");
        jbuttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Setor: ");

        jcbSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        jcbSetor.setToolTipText("Selecione o Setor onde será instalado");
        jcbSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSetorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Cadastro de Bem Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbuttonCancelar)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(72, 72, 72)
                            .addComponent(jbuttonSalvar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(entradaNumeroImobilizado))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(entradaSerialNumber))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(entradaFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcbNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(80, 80, 80)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel8)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entradaModelo)
                                .addComponent(jcbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcbUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(entradaFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jcbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(entradaSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(entradaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(entradaNumeroImobilizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonSalvar)
                    .addComponent(jbuttonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCancelarActionPerformed
        // TODO add your handling code here:
        int escolha = JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar o cadastro?", "Cancelar",JOptionPane.YES_NO_OPTION);
        if(escolha == JOptionPane.YES_OPTION){
            limparCampos();
        }else{
            
        }//fim do else  
    }//GEN-LAST:event_jbuttonCancelarActionPerformed

    private void jbuttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSalvarActionPerformed
        // TODO add your handling code here:
        //instanciar objeto //validar campos
        //preencher objeto  //salvar no banco
        objBemAtivo = new BemAtivoJar();
        
        try{
            if(validaCampos()){//inicio if valida
                if(preencherObjeto()){ //inicio if preenche
                    SalvarBemAtivo DAOsalvar = new SalvarBemAtivo();
                        DAOsalvar.salvarBem(objBemAtivo);
                        JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                        DAOsalvar.getConexao().close();
                        limparCampos();
                }   
            }
        }catch(SQLException ex){
            Logger.getLogger(BemAtivoJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jbuttonSalvarActionPerformed

    private void jcbNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNotaFiscalActionPerformed
        /* TODO add your handling code here:
        SalvarBemAtivo DAO = new SalvarBemAtivo();
        try{
            DefaultComboBoxModel jcbNF = new DefaultComboBoxModel(DAO.todasAsNotas().toArray());
            jcbNotaFiscal.setModel(jcbNF);
        }catch(SQLException ex){
            Logger.getLogger(NotaFiscalJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        
    }//GEN-LAST:event_jcbNotaFiscalActionPerformed

    private void jcbSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BemAtivoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BemAtivoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BemAtivoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BemAtivoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BemAtivoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane entradaDescricao;
    private javax.swing.JTextField entradaFabricante;
    private javax.swing.JTextField entradaModelo;
    private javax.swing.JTextField entradaNumeroImobilizado;
    private javax.swing.JTextField entradaSerialNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbuttonCancelar;
    private javax.swing.JButton jbuttonSalvar;
    private javax.swing.JComboBox jcbNotaFiscal;
    private javax.swing.JComboBox jcbSetor;
    private javax.swing.JComboBox jcbUnidade;
    // End of variables declaration//GEN-END:variables

private boolean validaCampos(){
    
    if(jcbNotaFiscal.getSelectedIndex() == -1){
        JOptionPane.showMessageDialog(this, "Selecione a Nota Fiscal.");
        jcbNotaFiscal.requestFocus();
        return false;
    }
    if(jcbUnidade.getSelectedIndex() == -1){
        JOptionPane.showMessageDialog(this, "Selecione a Unidade.");
        jcbUnidade.requestFocus();
        return false;
    }
    if(jcbSetor.getSelectedIndex() == -1){
        JOptionPane.showMessageDialog(this, "Selecione o Setor.");
        jcbSetor.requestFocus();
        return false;
    }
    if(entradaFabricante.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o Fabricante do produto..");
        entradaFabricante.requestFocus();
        return false;
    }
    if(entradaModelo.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o Modelo do produto..");
        entradaModelo.requestFocus();
        return false;
    }
    if(entradaSerialNumber.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o Número de Série do produto.");
        entradaSerialNumber.requestFocus();
        return false;
    }
    if(entradaNumeroImobilizado.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o Número do Imobilizado do produto.");
        entradaNumeroImobilizado.requestFocus();
        return false;
    }
    if(entradaDescricao.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Digite uma breve Descrição do produto.");
        entradaDescricao.requestFocus();
        return false;
    }
    return true;
}

private void limparCampos(){
    jcbNotaFiscal.setSelectedIndex(-1);
    jcbUnidade.setSelectedIndex(-1);
    jcbSetor.setSelectedIndex(-1);
    entradaFabricante.setText("");
    entradaModelo.setText("");
    entradaSerialNumber.setText("");
    entradaNumeroImobilizado.setText("");
    entradaDescricao.setText("");
    
}

private boolean preencherObjeto(){
    objBemAtivo = new BemAtivoJar();
    
    NotaFiscalJar nf = (NotaFiscalJar) jcbNotaFiscal.getSelectedItem();
    objBemAtivo.setNotaFiscal_idNotaFiscal(nf.getIdNotaFiscal());
    
    UnidadeJar uni = (UnidadeJar) jcbUnidade.getSelectedItem();
    objBemAtivo.setUnidadeDeInstalacao_idUnidadeDeInstalacao(uni.getIdUnidadeDeInstalacao());
    
    SetorJar set = (SetorJar) jcbSetor.getSelectedItem();
    objBemAtivo.setSetorDeInstalacao_idSetor(set.getIdSetor());
    
    objBemAtivo.setFabricante(entradaFabricante.getText());
    objBemAtivo.setModelo(entradaModelo.getText());
    objBemAtivo.setNumeroDeSerie(entradaSerialNumber.getText());
    objBemAtivo.setNumeroImobilizado(converteImobilizado());
    objBemAtivo.setDescricaoProduto(entradaDescricao.getText());
    
    
    return true;
}

private int converteImobilizado(){
    
    String numeroImobilizado;
    int nImobilizado;
    
    numeroImobilizado = entradaNumeroImobilizado.getText();
    nImobilizado = Integer.parseInt(numeroImobilizado);
    
    return nImobilizado;
}

}
