/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.NotaFiscalJFrame;
import GUI.FornecedoresJFrame;
import GUI.BemAtivoJFrame;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JFrame;

/**
 *
 * @author Home
 */
public class IndexJFrame extends javax.swing.JFrame {

    /**
     * Creates new form IndexJFrame
     */
    public IndexJFrame() {
        setExtendedState(JFrame.MAXIMIZED_BOTH); //para abrir em modo tela cheia
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jItemFornecedor = new javax.swing.JMenu();
        jSubItemFornecedor = new javax.swing.JMenuItem();
        jSubItemEnd = new javax.swing.JMenuItem();
        jItemNotaFiscal = new javax.swing.JMenuItem();
        jItemBemAtivo = new javax.swing.JMenuItem();
        jItemLicenca = new javax.swing.JMenuItem();
        jmConsulta = new javax.swing.JMenu();
        jmiConsultaFornecedor = new javax.swing.JMenuItem();
        jmConfig = new javax.swing.JMenu();
        jItemUnidade = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IquisCbaII");

        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iquiscbaii/img/caneta.png"))); // NOI18N
        jMenuCadastro.setText("Cadastro");

        jItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/fornecedor.png"))); // NOI18N
        jItemFornecedor.setText("Fornecedor");

        jSubItemFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jSubItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iquiscbaii/img/fornecedor.png"))); // NOI18N
        jSubItemFornecedor.setText("Fornecedor");
        jSubItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubItemFornecedorActionPerformed(evt);
            }
        });
        jItemFornecedor.add(jSubItemFornecedor);

        jSubItemEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/fornecedor.png"))); // NOI18N
        jSubItemEnd.setText("Endereço");
        jSubItemEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubItemEndActionPerformed(evt);
            }
        });
        jItemFornecedor.add(jSubItemEnd);

        jMenuCadastro.add(jItemFornecedor);

        jItemNotaFiscal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jItemNotaFiscal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/nf16.png"))); // NOI18N
        jItemNotaFiscal.setText("Nota Fiscal");
        jItemNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemNotaFiscalActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jItemNotaFiscal);

        jItemBemAtivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jItemBemAtivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/comp16.png"))); // NOI18N
        jItemBemAtivo.setText("Bem Ativo");
        jItemBemAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemBemAtivoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jItemBemAtivo);

        jItemLicenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/soft16.png"))); // NOI18N
        jItemLicenca.setText("Licença de Software");
        jItemLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemLicencaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jItemLicenca);

        jMenuBar1.add(jMenuCadastro);

        jmConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iquiscbaii/img/lupa.png"))); // NOI18N
        jmConsulta.setText("Consulta");

        jmiConsultaFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/fornecedor.png"))); // NOI18N
        jmiConsultaFornecedor.setText("Fornecedores");
        jmiConsultaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaFornecedorActionPerformed(evt);
            }
        });
        jmConsulta.add(jmiConsultaFornecedor);

        jMenuBar1.add(jmConsulta);

        jmConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iquiscbaii/img/config.png"))); // NOI18N
        jmConfig.setText("Configuração");

        jItemUnidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jItemUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/unidade.png"))); // NOI18N
        jItemUnidade.setText("Unidade");
        jItemUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemUnidadeActionPerformed(evt);
            }
        });
        jmConfig.add(jItemUnidade);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/dir16.png"))); // NOI18N
        jMenuItem1.setText("Setor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmConfig.add(jMenuItem1);

        jMenuBar1.add(jmConfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItemNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemNotaFiscalActionPerformed
        // TODO add your handling code here:
        new NotaFiscalJFrame().setVisible(true);
    }//GEN-LAST:event_jItemNotaFiscalActionPerformed

    private void jItemBemAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemBemAtivoActionPerformed
        // TODO add your handling code here:
        new BemAtivoJFrame().setVisible(true);
    }//GEN-LAST:event_jItemBemAtivoActionPerformed

    private void jItemUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemUnidadeActionPerformed
        // TODO add your handling code here:
        new UnidadeJFrame().setVisible(true);
    }//GEN-LAST:event_jItemUnidadeActionPerformed

    private void jSubItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubItemFornecedorActionPerformed
        // TODO add your handling code here:
        new FornecedoresJFrame().setVisible(true);

    }//GEN-LAST:event_jSubItemFornecedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new SetorJFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jSubItemEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubItemEndActionPerformed
        // TODO add your handling code here:
        //alterar...
        new FornecedoresJFrame().setVisible(false);
    }//GEN-LAST:event_jSubItemEndActionPerformed

    private void jItemLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemLicencaActionPerformed
        // TODO add your handling code here:
        new LicencaJFrame().setVisible(true);
    }//GEN-LAST:event_jItemLicencaActionPerformed

    private void jmiConsultaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaFornecedorActionPerformed
        // TODO add your handling code here:
        new ConsultaFornecedor().setVisible(true);
    }//GEN-LAST:event_jmiConsultaFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jItemBemAtivo;
    private javax.swing.JMenu jItemFornecedor;
    private javax.swing.JMenuItem jItemLicenca;
    private javax.swing.JMenuItem jItemNotaFiscal;
    private javax.swing.JMenuItem jItemUnidade;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jSubItemEnd;
    private javax.swing.JMenuItem jSubItemFornecedor;
    private javax.swing.JMenu jmConfig;
    private javax.swing.JMenu jmConsulta;
    private javax.swing.JMenuItem jmiConsultaFornecedor;
    // End of variables declaration//GEN-END:variables
}
