/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dataBase.ConectaDB;
import dataBase.SalvarUnidade;
import iquiscbaii.UnidadeJar;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Home
 */
public class UnidadeJFrame extends javax.swing.JFrame {
    
    UnidadeJar objUni;
    ConectaDB con;
    
    /**
     * Creates new form UnidadeJFrame
     */
    public UnidadeJFrame() {
//        preencheTabela();
        initComponents();
        setLocationRelativeTo(null);
        
//        URL url = this.getClass().getResource("./img/unidade.png");
//        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
//        this.setIconImage(imagemTitulo);
        
        preencheTabela();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entradaUnidade = new javax.swing.JTextField();
        jbtSalvar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jspScroll = new javax.swing.JScrollPane();
        jtbTabelaUnidade = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Unidade");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Cadastro de Unidade");

        jLabel2.setText("Unidade:");

        entradaUnidade.setToolTipText("Informe a nova Unidade");

        jbtSalvar.setText("Salvar");
        jbtSalvar.setToolTipText("Clique para Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtCancelar.setText("Cancelar");
        jbtCancelar.setToolTipText("Clique para Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jtbTabelaUnidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Unidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspScroll.setViewportView(jtbTabelaUnidade);
        if (jtbTabelaUnidade.getColumnModel().getColumnCount() > 0) {
            jtbTabelaUnidade.getColumnModel().getColumn(0).setMinWidth(60);
            jtbTabelaUnidade.getColumnModel().getColumn(0).setPreferredWidth(65);
            jtbTabelaUnidade.getColumnModel().getColumn(0).setMaxWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(entradaUnidade)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(entradaUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSalvar)
                    .addComponent(jbtCancelar))
                .addGap(18, 18, 18)
                .addComponent(jspScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        // TODO add your handling code here:
        objUni = new UnidadeJar();
        
        if(validarCampos()){
            if(preencherObjeto()){
                
                SalvarUnidade DAO = new SalvarUnidade();
                try{
                    DAO.salvar(objUni);
                    JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                    DAO.getConexao().close();
                    limparCampos(); //limpar os campos após salvar no banco
                    
                }catch(SQLException ex) {
                    Logger.getLogger(UnidadeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    
                }
                
                limparCampos();
            }
        }
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        // TODO add your handling code here:
        int escolha = JOptionPane.showConfirmDialog(this, "Deseja relamente cancelar o cadastro?", "Cancelar", JOptionPane.YES_NO_OPTION);
        if (escolha == JOptionPane.YES_OPTION) {
            //new FornecedoresJFrame().setVisible(true);
            limparCampos();
        } else {
            //não confirmou
        }
    }//GEN-LAST:event_jbtCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnidadeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entradaUnidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JScrollPane jspScroll;
    private javax.swing.JTable jtbTabelaUnidade;
    // End of variables declaration//GEN-END:variables

    private boolean preencherObjeto(){
        objUni = new UnidadeJar();
        
        objUni.setUnidade(entradaUnidade.getText());
        
        return true;
    }
    
    private boolean validarCampos(){
        
        if(entradaUnidade.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Informe a Unidade.");
            entradaUnidade.requestFocus();
            return false;
        }
        
        return true;
    }
    
    private void limparCampos(){
        
      entradaUnidade.setText("");
        
    }
    
    private void preencheTabela(){
        SalvarUnidade DAOConsulta = new SalvarUnidade();
        UnidadeJar uni = new UnidadeJar();
        DefaultTableModel modeloTU = (DefaultTableModel) jtbTabelaUnidade.getModel();

        try{
            List<UnidadeJar> todasUnidades = DAOConsulta.ConsultaTudo();
            
            for(UnidadeJar unidade : todasUnidades)
            {
                modeloTU.addRow(new Object[] {unidade.getIdUnidadeDeInstalacao(),unidade.getUnidade()});
            }
        }catch(SQLException ex) {
                    Logger.getLogger(UnidadeJFrame.class.getName()).log(Level.SEVERE, null, ex);

        }


    }


}
