/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iquiscbaii;

/**
 *
 * @author casa
 */
public class CancelarFornecedoresJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CancelarFornecedoresJFrame
     */
    public CancelarFornecedoresJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMensagem = new javax.swing.JLabel();
        buttonNao = new javax.swing.JButton();
        buttonSim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cancelar");

        labelMensagem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMensagem.setText("Deseja realmente cancelar?");

        buttonNao.setBackground(new java.awt.Color(255, 255, 255));
        buttonNao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonNao.setForeground(new java.awt.Color(0, 102, 0));
        buttonNao.setText("Não");
        buttonNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNaoActionPerformed(evt);
            }
        });

        buttonSim.setBackground(new java.awt.Color(255, 255, 255));
        buttonSim.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonSim.setForeground(new java.awt.Color(0, 102, 0));
        buttonSim.setText("Sim");
        buttonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(buttonNao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSim)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(labelMensagem)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNao)
                    .addComponent(buttonSim))
                .addGap(22, 22, 22))
        );

        getAccessibleContext().setAccessibleName("CancelarFornecedores");
        getAccessibleContext().setAccessibleDescription("Cancelar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonSimActionPerformed

    private void buttonNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNaoActionPerformed
        // TODO add your handling code here:
        new ForncedoresJFrame().setVisible(true);
    }//GEN-LAST:event_buttonNaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelarFornecedoresJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelarFornecedoresJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelarFornecedoresJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelarFornecedoresJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelarFornecedoresJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNao;
    private javax.swing.JButton buttonSim;
    private javax.swing.JLabel labelMensagem;
    // End of variables declaration//GEN-END:variables
}
