package iquiscbaii;

import dataBase.SalvarNotaFiscal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class NotaFiscalJFrame extends javax.swing.JFrame {
    
    FornecedoresJar objFornecedor;
    NotaFiscalJar objNF;

    /**
     * Creates new form NotaFiscalJFrame
     */
    public NotaFiscalJFrame() {
        initComponents();
        SalvarNotaFiscal DAO = new SalvarNotaFiscal();
        try{
            DefaultComboBoxModel jcbSelecione = new DefaultComboBoxModel(DAO.todosFornecedores().toArray());
            jcbSelecioneFornecedor.setModel(jcbSelecione);
        }catch(SQLException ex){
            Logger.getLogger(NotaFiscalJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        entradaNumeroNotaFiscal = new javax.swing.JTextField();
        jcbSelecioneFornecedor = new javax.swing.JComboBox();
        buttonPesquisarNotaFiscal = new javax.swing.JButton();
        entradaCaminhoArquivo = new javax.swing.JTextField();
        jbuttonSalvar = new javax.swing.JButton();
        jbuttonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fornecedor: ");

        jLabel2.setText("Número Nota Fiscal: ");

        jLabel3.setText("Imagem:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 9)); // NOI18N
        jLabel4.setText("Insira um arquivo de imagem da Nota Fiscal");

        entradaNumeroNotaFiscal.setToolTipText("Informe o número da Nota Fiscal");

        jcbSelecioneFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        jcbSelecioneFornecedor.setToolTipText("Selecione o Fornecedor emitente da Nota Fiscal a ser cadastrada");
        jcbSelecioneFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSelecioneFornecedorActionPerformed(evt);
            }
        });

        buttonPesquisarNotaFiscal.setText("Pesquisar");
        buttonPesquisarNotaFiscal.setToolTipText("Pesquise a imagem da Nota Fiscal");
        buttonPesquisarNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarNotaFiscalActionPerformed(evt);
            }
        });

        entradaCaminhoArquivo.setToolTipText("Informe o caminho da imagem da Nota Fiscal(Formato JPG, PNG ou BMP)");

        jbuttonSalvar.setText("Salvar");
        jbuttonSalvar.setToolTipText("Clique para salvar o cadastro da Nota Fiscal");
        jbuttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSalvarActionPerformed(evt);
            }
        });

        jbuttonCancelar.setText("Cancelar");
        jbuttonCancelar.setToolTipText("Clique para cancelar o cadastro da Nota Fiscal");
        jbuttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaNumeroNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbuttonCancelar)
                                        .addGap(36, 36, 36)
                                        .addComponent(jbuttonSalvar))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jcbSelecioneFornecedor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(entradaCaminhoArquivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(buttonPesquisarNotaFiscal)))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbSelecioneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(entradaNumeroNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(entradaCaminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPesquisarNotaFiscal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonSalvar)
                    .addComponent(jbuttonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPesquisarNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisarNotaFiscalActionPerformed
        // TODO add your handling code here:
        JFileChooser escolhaArquivo = new JFileChooser();
        int escolha = escolhaArquivo.showOpenDialog(getParent());
        entradaCaminhoArquivo.setText(escolhaArquivo.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_buttonPesquisarNotaFiscalActionPerformed

    private void jbuttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSalvarActionPerformed
        // TODO add your handling code here:
        objNF = new NotaFiscalJar();
        
        if(validaCampos()){
            //Se os campos estiverem devidamente preenchidos, o próximo passo será executado....
            if(preencherForm()){
                //se conseguir preencher o objeto...
                SalvarNotaFiscal DAO2 = new SalvarNotaFiscal();
                try{
                    if(DAO2.salvarNF(objNF)){
                        JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                        DAO2.getConexao().close();
                        limparCampos();
                    }else{
                        JOptionPane.showMessageDialog(this, "Não foi possível salvar as informações!");
                        DAO2.getConexao().close();
                    }
                }catch(SQLException ex){
                    Logger.getLogger(ForncedoresJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
    }//GEN-LAST:event_jbuttonSalvarActionPerformed

    private void jbuttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCancelarActionPerformed
        // TODO add your handling code here:
        int escolha = JOptionPane.showConfirmDialog(this, "Deseja relamente cancelar o cadastro?", "Cancelar", JOptionPane.YES_NO_OPTION);
        if(escolha == JOptionPane.YES_OPTION){
            limparCampos();
        }
    }//GEN-LAST:event_jbuttonCancelarActionPerformed

    private void jcbSelecioneFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSelecioneFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSelecioneFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaFiscalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPesquisarNotaFiscal;
    private javax.swing.JTextField entradaCaminhoArquivo;
    private javax.swing.JTextField entradaNumeroNotaFiscal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbuttonCancelar;
    private javax.swing.JButton jbuttonSalvar;
    private javax.swing.JComboBox jcbSelecioneFornecedor;
    // End of variables declaration//GEN-END:variables
    
    //converter String para inteiro
    private int converteNumeroNF(){
        String numberNF;
        int numberNFConvert;
        numberNF = entradaNumeroNotaFiscal.getText();
        
        numberNFConvert = Integer.parseInt(numberNF);
        
        return numberNFConvert;
    }
    
    private boolean preencherForm(){
        objNF = new NotaFiscalJar();
        
        System.out.println(jcbSelecioneFornecedor.getSelectedItem());
        FornecedoresJar f = (FornecedoresJar) jcbSelecioneFornecedor.getSelectedItem();
        objNF.setFornecedores_idFornecedores(f.getIdFornecedores());
        objNF.setNumeroNF(converteNumeroNF());
        objNF.setImagemNF(entradaCaminhoArquivo.getText());
        
        return true;
    }
    
    private boolean validaCampos(){
        if(jcbSelecioneFornecedor.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Selecione o Fornecedor.");
            return false;
        }
        if(entradaNumeroNotaFiscal.getText().equals("") || entradaNumeroNotaFiscal.getText().equals(null)){
            JOptionPane.showMessageDialog(this, "Informe o número da Nota Fiscal.");
            return false;
        }
        if(entradaCaminhoArquivo.getText().equals("") || entradaCaminhoArquivo.getText().equals(null)){
            JOptionPane.showMessageDialog(this, "Informe a imagem da Nota Fiscal");
            return false;
        }
        return true;
    }
    
    private void limparCampos(){
        jcbSelecioneFornecedor.setSelectedIndex(0);
        entradaNumeroNotaFiscal.setText("");
        entradaCaminhoArquivo.setText("");
                
    }

}
